name: "📝 Description"
description: General issue, question, or discussion topic
title: "[Description]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for general issues, questions, or topics that don't fit into bug reports or feature requests.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a clear and concise summary of the issue or topic.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Elaborate on the issue with as much detail as needed.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which part of the project does this relate to (if any)?
      options:
        - Library (`library/`)
        - Prototype / Streamlit app (`prototype/`)
        - Data pipeline (`data/`)
        - Analysis / Notebooks (`analysis/`)
        - Documentation (`docs/`)
        - General / Not specific
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context, links, or references.
    validations:
      required: false
